; Upload over HTTP:
;   pio run -e lolin32
;   curl --data-binary @.pio/build/lolin32/firmware.bin http://<device-ip>/update
[platformio]
default_envs = lolin32
extra_configs = ../../secrets.ini

[env]
platform = espressif32@6.9.0
framework = arduino
board_build.partitions = ../../partitions_4mb.csv
monitor_speed = 115200
lib_extra_dirs = ../../lib
lib_deps =
    esp32async/AsyncTCP@^3.3.2
    esp32async/ESPAsyncWebServer@^3.7.0

[env:wt32-eth01]
board = wt32-eth01
build_flags =
    -DEASYOTA_USE_ETH

; The lolin board is supported for development purposes
[env:lolin32]
board = lolin32
build_flags =
    -DEASYOTA_USE_WIFI
    -DEASYOTA_WIFI_SSID='"${secrets.wifi_ssid}"'
    -DEASYOTA_WIFI_PASS='"${secrets.wifi_pass}"'
monitor_port = /dev/ttyACM0
